# general configuration
url: https://gbarbu.eu
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/profile.jpg"
  # author will appear under the avatar (optional)
  author: "Gabriel Barbu"
  description: "About Gabriel Barbu"
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "bibistroc"

links:
  - text: "Codecamp 2022"
    url: /conferences/codecamp2022
  - text: "GDG DevFest Craiova 2019"
    url: /conferences/gdgCraiova2019
  - text: "K&M Craiova 2018"
    url: /conferences/kmCraiova2018
  - text: "K&M Sibiu 2018"
    url: /conferences/kmSibiu2018
  - text: "K&M Craiova 2017"
    url: /conferences/kmCraiova2017
  - text: "Contact"
    url: /contact

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
